// barangay.ts

export const barangay: string[] = [
    'Arena Blanco',
    'Ayala',
    'Baluno',
    'Boalan',
    'Bolong',
    'Buenavista',
    'Bunguiao',
    'Busay',
    'Cabaluay',
    'Cabatangan',
    'Cacao',
    'Calabasa',
    'Camino Nuevo',
    'Canelar',
    'Capisan',
    'Cawit',
    'Dulian (Upper Pasonanca)',
    'Dulian (Upper Pasonanca)',
    'Guisao',
    'Labuan',
    'Lamisahan',
    'Landang Gua',
    'Landang Laum',
    'Lanzones',
    'Lapakan',
    'La Paz',
    'Limaong',
    'Limpapa',
    'Luba',
    'Lumayang',
    'Lunzuran',
    'Maasin',
    'Mabuhay',
    'Malagutay',
    'Mampang',
    'Manalipa',
    'Mangusu',
    'Manicahan',
    'Mariki',
    'Mercedes',
    'Mutia',
    'Pamucutan',
    'Panubigan',
    'Pasilmanta',
    'Pasobolong',
    'Patalon',
    'Pasonanca',
    'Patalon',
    'Putik',
    'Quiniput',
    'Recodo',
    'Rio Hondo',
    'San Jose Gusu',
    'San Jose Cawa-Cawa',
    'San Roque',
    'Santa Barbara',
    'Santa Catalina',
    'Santa Maria',
    'Santo Niño',
    'Sibulao Curuan',
    'Sinunuc',
    'Tagasilay',
    'Talabaan',
    'Talisayan',
    'Talon-Talon',
    'Taluksangay',
    'Tetuan',
    'Tictapul',
    'Victoria',
    'Vitali',
    'Zambowood',
  ];
  