import './globals.css';
import {Inter} from 'next/font/google';

import AuthProvider from "@/components/Auth/Authprovider";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs"
import { cookies } from "next/headers"
import NavBar from '@/components/Header/navBarLinkServer';
import Footer from '@/components/Pages/footer';

export const inter = Inter({ subsets: ['latin'] });

//tried adding this
export const revalidate = 0;
export const dynamic = "force-dynamic";

export const metadata = {
  title: 'Water Refilling Station',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const supabase = createServerComponentClient({cookies});

  const {
    data: { session },
  } = await supabase.auth.getSession();

  const accessToken = session?.access_token || null;
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
      <NavBar session={session}/>
      <div className= "relative isolate px-6 pt-14 lg:px-8">
        <AuthProvider accessToken={accessToken}>{children}</AuthProvider>  
      </div>
      
        <Footer/>
      </body>
    </html>
  )
}
